Repository hyperledger/fabric-x-committer, pull requests merged in 2025-07, with the labels that each got.

#66 Remove unused files
  .travis.yml
  .whitesource
  scripts/ci-flow.sh
  scripts/init-private-git.sh
Labels: code-hygiene

#64 [BREAKING] Fix TX ASN1 digest
  .github/workflows/ci.yml
  .sqlfluff
  Makefile
  api/protoblocktx/block_tx.pb.go
  api/protoblocktx/block_tx.proto
  api/protoqueryservice/query.pb.go
  api/protoqueryservice/query.proto
  api/types/height.go
  api/types/types.go
  go.mod
  integration/runner/runtime.go
  integration/test/config_update_test.go
  integration/test/dependency_test.go
  integration/test/namespace_lifecycle_test.go
  integration/test/query_service_test.go
  integration/test/service_crash_test.go
  integration/test/valid_invalid_sign_mix_test.go
  loadgen/client.go
  loadgen/workload/conflicts.go
  loadgen/workload/namespace.go
  loadgen/workload/stream_test.go
  loadgen/workload/tx.go
  service/coordinator/coordinator_test.go
  service/coordinator/dependencygraph/global_dependency_manager.go
  service/query/query.go
  service/query/query.sql
  service/query/query_service_test.go
  service/sidecar/mapping.go
  service/vc/committer.go
  service/vc/committer_test.go
  service/vc/create_insert_ns_states_func_templ.sql
  service/vc/create_insert_tx_status_func.sql
  service/vc/create_namespace.sql
  service/vc/create_update_ns_states_func_templ.sql
  service/vc/create_validate_func_templ.sql
  service/vc/database.go
  service/vc/database_test.go
  service/vc/dbinit.go
  service/vc/dbinit_test.go
  service/vc/dbtest/container.go
  service/vc/init_database.sql
  service/vc/preparer.go
  service/vc/preparer_test.go
  service/vc/test_exports.go
  service/vc/validator.go
  service/vc/validator_committer_service_test.go
  service/vc/validator_test.go
  service/verifier/test_exports.go
  service/verifier/verifier_server_test.go
  service/verifier/verify.go
  utils/signature/block_tx.go
  utils/signature/block_tx_test.go
  utils/signature/sigtest/bench_test.go
  utils/signature/sigtest/factory_test.go
  utils/signature/sigtest/signer.go
  utils/signature/tx_schema.asn
  utils/signature/verify.go
  utils/signature/verify_dummy.go
Labels: bug, security

#74 [docs] validator-committer service
  docs/validator-committer.md
Labels: documentation

#78 [BREAKING] Modify naming and numbering of status codes
  .gotestfmt/travisci/package.gotpl
  Makefile
  api/protoblocktx/block_tx.pb.go
  api/protoblocktx/block_tx.proto
  api/protocoordinatorservice/coordinator.pb.go
  api/protocoordinatorservice/coordinator.proto
  integration/runner/runtime.go
  integration/test/badly_formed_txs_test.go
  integration/test/service_crash_test.go
  loadgen/adapters/sidecar_receiver.go
  loadgen/workload/stream_test.go
  mock/coordinator.go
  service/coordinator/coordinator.go
  service/coordinator/coordinator_test.go
  service/coordinator/dependencygraph/dependency_detector.go
  service/coordinator/dependencygraph/transaction_node.go
  service/coordinator/metrics.go
  service/sidecar/ledger_service_test.go
  service/sidecar/mapping.go
  service/sidecar/mapping_test.go
  service/sidecar/relay.go
  service/sidecar/relay_test.go
  service/sidecar/sidecar.go
  service/sidecar/sidecar_test.go
  service/sidecar/test_exports.go
  service/vc/committer.go
  service/vc/committer_test.go
  service/vc/database.go
  service/vc/preparer_test.go
  service/vc/test_exports.go
  service/vc/validator_committer_service.go
  service/vc/validator_committer_service_test.go
  service/vc/validator_test.go
  service/verifier/policy/policy.go
  service/verifier/test_exports.go
  service/verifier/verifier_server.go
  service/verifier/verifier_server_test.go
  service/verifier/verify.go
  service/verifier/verify_test.go
  utils/serialization/envelope_wrapper.go
  utils/signature/verify.go
  utils/utils.go
Labels: bug, breaking
